name: APK Yapici

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Kodu Cek
      uses: actions/checkout@v4

    - name: Sistem Paketlerini Kur
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential ccache git zlib1g-dev libncurses5-dev libgdbm-dev libnss3-dev libssl-dev libreadline-dev libsqlite3-dev libffi-dev wget curl libbz2-dev openjdk-17-jdk-headless unzip
        # Kivy ve Buildozer icin ekstra gereken grafik/derleme paketleri:
        sudo apt-get install -y libsdl2-dev libsdl2-image-dev libsdl2-mixer-dev libsdl2-ttf-dev libgl1-mesa-dev libgles2-mesa-dev python3-setuptools pkg-config

    - name: Python Kur
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Buildozer ve Cython Kur
      run: |
        pip install --upgrade pip
        pip install "cython<3.0.0"
        pip install buildozer kivy

    - name: APK'yi Uret (Bu biraz zaman alabilir)
      run: |
        buildozer android debug

    - name: APK Dosyasini Yukle
      uses: actions/upload-artifact@v4
      with:
        name: Jarvis-AI-APK
        path: bin/*.apk
